Add JaCoCo and integration tests
jenkinsci/remoting-kafka-plugin pull request #76
Opened 2019-08-16 13:31 UTC by longngn

2019-08-18 14:53 UTC, longngn commented
@afalko I think this is ready to be merged, can you check it?

2019-08-19 05:25 UTC, afalko commented on plugin/src/test/java/io/jenkins/plugins/remotingkafka/KafkaKubernetesCloudTest.java
> +        TimeUnit.SECONDS.sleep(20);
Hmmm...this seems like a long sleep...could you poll, sleep for 1 second and timeout polling after 30 instead?

2019-08-19 05:25 UTC, afalko requested changes
If you can, improve the long sleep by polling

2019-08-19 06:14 UTC, afalko approved these changes

2019-08-19 06:14 UTC, merged